# Name of the application
name: ghost

# Service type
type: nodejs:10

# Web configuration
web:
    commands:
        start: "node_modules/.bin/ghost start"

    locations:
        "/":
            passthru: false
            root: "ghost"
            # Whether to allow files not matching a rule or not.
            allow: true
            rules:
                '\.png$':
                    allow: true
                    expires: -1

hooks:
    build: |

        ln -sfn node_modules/ghost ghost
        cp config/config.production.json ghost/config.production.json

#        node_modules/.bin/ghost install --dir build
#       On the first install we need to set up the content directories properly.
#        cd run
#        if [ ! -f .installed ]; then
#            cd ..
#            cp -R build/content ghost/content
#            cd run
#            touch .installed
#        fi

# File mounts
mounts:
    'run':
        source: local
        source_path: run
    'ghost/content':
        source: local
        source_path: 'content'

# File mounts storage
disk: 512