# Name of the application
name: ghost

# Service type
type: nodejs:10
dependencies:
    nodejs:
        pm2: "^2.5.0"

# Services
relationships:
    database: 'mysqldb:primary'

# Web configuration
web:
    commands:
        start: "NODE_ENV=production PM2_HOME=$PLATFORM_APP_DIR/run pm2 start ghost/index.js --no-daemon"

    locations:
        "/":
            passthru: false
            root: "ghost"
            # Public files
            allow: true
            rules:
                \.(css|js|gif|jpe?g|png|ttf|eot|woff2?|otf|html|ico|svg?)$:
                    allow: true
                ^/robots\.txt$:
                    allow: true

hooks:
    build: |
        ln -sfn node_modules/ghost ghost
        cp config/config.production.json ghost/config.production.json

        # On the first install we need to set up the content directories properly. As they will be overwritten by a mount
        # in the next phase, copy them now in case we need them.
        mkdir tmp
        cp -R ghost/content tmp/content
        rm -rf ghost/content

    deploy: |
        # On the first install we need to set up the content directories properly. By this point content will be a mount,
        # and either empty (new) or have content (installed).
        if find ghost/content -mindepth 1 | read; then
            echo "content directory exists"
        else
            echo "content directory does not exist, copying from source"
            cp -R tmp/content ghost
        fi

# File mounts
mounts:
    'run':
        source: local
        source_path: run
    'ghost/content':
        source: local
        source_path: 'content'

# File mounts storage
disk: 512